### ISSUE TITLE
V2 Objectives (Copied from TODO)

### ISSUE THREAD

**Issue by MatthewRizzo** [MatthewRizzo/RustHSM#1]
# TODO for v2

Create issues based on this one and link them here!

Main Aims:

* improve ease of use
* Reduce complexity of data structures
* Cleanup any bugs

## Action Items (AI)

1. [x] Use swap to replace change state request in `get_and_reset_requested_state_change`
2. [x] Remove controller from states - See #5
   1. Kind of gross that it is there right now. Not sure if used.
3. [x] Move `requested_state_change` API to `StateChainOfResponsibility` instead of `ComposableStateData`
   1. Tie it to API, not a specific data structure
4. [ ] Create a macro called `change_state!(target_state)`
   1. so that user's dont have to call it themselves / know how it works.
5. [x] Try to remove the `Rc`'s / `RefCell's` if possible.
   1. Now that we know the impl works, try to minimize as much of the "cludge" as possible
   2. [x] Done for `HsmController` as part of #5.
   3. [x] MANY were done within #7. Much more of a single-ownership model now.
6. [ ] Add actual tests!
    1. Started with #7 but more work is needed!
8. [x] De-couple `StateChainOfResponsibility` from `ComposableStateData` (if possible)
9. [ ] Apply clippy suggestions
10. [x] Have an easy way for HSM to convert state id to name (for logging purposes)
11. [x] Genericize Events the same way states were (if possible) - Completed by #9 
12. [ ] Add some plantuml diagrams for the architecture of delegates.
    1. [ ] Bonus if we can add a github action to display the rendered diagram in our wiki page!
13. [ ] Setup GitHub Actions to run `cargo clippy` + `cargo fmt` on every PR
14. [ ] Devise a method for the hsm to be woken up if anyone puts a request on the queue
